# Site Settings
lang: en
icon: ğŸŸ
title: Pond
description: Welcome to the Small Web

url: "https://megdna.github.io"
baseurl: "/pond"
permalink: :title
goatcounter: meg

nav:
  - name: About
    link: /about
  - name: Posts
    link: /posts
  
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  -
    scope:
      path: "media/**"
    values:
      sitemap: false