# SEO Stuff
lang: en

repo: "https://github.com/megdna/pond"
url: "https://megdna.github.io"
baseurl: "/pond"

permalink: :title
title: Pond
description: Welcome to the Small Web

author: 
emoji: ğŸŸ
goatcounter: git

nav:
- name: Home
  link: /
- name: About
  link: /about
- name: Blog
  link: /blog
  
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap