# Site Settings
title: Pond
description: Welcome to the Small Web
url: "https://megdna.github.io"
baseurl: "/pond"
permalink: :title

author: Megan
github: megdna
goatcounter: meg
icon: ğŸŸ
lang: en

nav:
  - name: Home
    link: /
  - name: About
    link: /about
  - name: Blog
    link: /blog
  
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap